### ISSUE TITLE
Failure to build due to Dependencies

### ISSUE THREAD

**Issue by RobertLHarris** [eccentricdevotion/TARDISChunkGenerator#1]
{0}:/usr/local/minecraft/PluginsBySource/TARDISChunkGenerator>date; echo; grep -i url .git/config; echo ; git pull; echo; mvn install
Thu Aug 16 15:24:28 MDT 2018

        url = https://github.com/eccentricdevotion/TARDISChunkGenerator.git

Already up to date.

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building TARDISChunkGenerator 4.0.2
[INFO] ------------------------------------------------------------------------
Downloading from macgeek: http://tardisjenkins.duckdns.org:8888/org/bukkit/craftbukkit/1.13-R0.1-SNAPSHOT/maven-metadata.xml
**[WARNING] Could not transfer metadata org.bukkit:craftbukkit:1.13-R0.1-SNAPSHOT/maven-metadata.xml from/to macgeek (http://tardisjenkins.duckdns.org:8888): Connect to tardisjenkins.duckdns.org:8888 [tardisjenkins.duckdns.org/203.173.188.138] failed: Connection timed out (Connection timed out)**
[WARNING] Failure to transfer org.bukkit:craftbukkit:1.13-R0.1-SNAPSHOT/maven-metadata.xml from http://tardisjenkins.duckdns.org:8888 was cached in the local repository, resolution will not be reattempted until the update interval of macgeek has elapsed or updates are forced. Original error: Could not transfer metadata org.bukkit:craftbukkit:1.13-R0.1-SNAPSHOT/maven-metadata.xml from/to macgeek (http://tardisjenkins.duckdns.org:8888): Connect to tardisjenkins.duckdns.org:8888 [tardisjenkins.duckdns.org/203.173.188.138] failed: Connection timed out (Connection timed out)
Downloading from macgeek: http://tardisjenkins.duckdns.org:8888/org/bukkit/craftbukkit/1.13-R0.1-SNAPSHOT/craftbukkit-1.13-R0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:23 min
[INFO] Finished at: 2018-08-16T15:29:01-06:00
[INFO] Final Memory: 9M/151M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project TARDISChunkGenerator: Could not resolve dependencies for project me.eccentric_nz.tardischunkgenerator:TARDISChunkGenerator:jar:4.0.2: Failed to collect dependencies at org.bukkit:craftbukkit:jar:1.13-R0.1-SNAPSHOT: Failed to read artifact descriptor for org.bukkit:craftbukkit:jar:1.13-R0.1-SNAPSHOT: Could not transfer artifact org.bukkit:craftbukkit:pom:1.13-R0.1-SNAPSHOT from/to macgeek (http://tardisjenkins.duckdns.org:8888): Connect to tardisjenkins.duckdns.org:8888 [tardisjenkins.duckdns.org/203.173.188.138] failed: Connection timed out (Connection timed out) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by eccentricdevotion** [comment]
Edit the pom.xml file and remove the tardis jenkins.duckdns.org:8888 repository, and make sure CraftBukkit is in your local maven repo (it should be if you've ever run Spigot's BuildTools)
Alternatively, just use the continuous integration server to get the latest builds:
http://tardisjenkins.duckdns.org:8080
