### ISSUE TITLE
Some kind of worldgen warning.

### ISSUE THREAD

**Issue by MagmaSlime123** [eccentricdevotion/TARDISChunkGenerator#8]
### Describe the bug

Title. TCG likes to spam a few errors upon server startup.

### To Reproduce

Start the server.

### Screenshots

N/A

### Log files

https://pastebin.com/MwX3wwSR

### '/tardis version' output

![2022-12-26_21 40 22](https://user-images.githubusercontent.com/51277766/209612038-6508f795-d2e1-4f36-8ce3-2f0a2715b55c.png)

**Comment by eccentricdevotion** [comment]
Not errors, warnings...

**Comment by eccentricdevotion** [comment]
> [18:35:14 WARN]: Potential async entity add during worldgen

The chunk generator code that is throwing the warning does not add entities

**Comment by MagmaSlime123** [comment]
Well, something hates TCG

**Comment by eccentricdevotion** [comment]
Build 175

**Comment by MagmaSlime123** [comment]
Lemme guess, something in TCG hated whatever was going on?

**Comment by eccentricdevotion** [comment]
TCG was just calling a Mojang method (the same one that is used by Vanilla Minecraft to grow huge fungus trees). My guess is that Spigot/Paper/Pufferfish doesn't expect a plugin to call the same method and was flagging it as a warning for doing something that it thought was unusual. Probably more of a Spigot bug than a TCG one IMO.

I just switched to using a different Mojang method (one that was called by the original method I was using internally anyway) and bypassed a few lines of vanilla code - no more warnings :)

**Comment by MagmaSlime123** [comment]
Ah.
